package fibonacci;

import java.util.List;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p/>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2 {


    public static void main(String[] args) {

        long sum = 0;

        long first = 0;
        long second = 1;

        long result = 0;

        boolean run = true;

        while (run) {

            sum = first + second;

            if (sum >= 4000000) {
                run = false;
            } else {
                if ((sum) % 2 == 0) {
                    result = result + sum;
                }

                first = second;
                second = sum;
            }
        }

        System.out.print("We got sum " + result);

    }
}
