package triangle;

import java.util.ArrayList;
import java.util.List;

import com.sun.xml.internal.bind.v2.schemagen.xmlschema.*;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * <p/>
 * The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p/>
 * Let us list the factors of the first seven triangle numbers:
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * <p/>
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p/>
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem12 {

    public static void main(String[] args) {

        long time = System.currentTimeMillis();

        int triangleNumber = 0;
        boolean run = true;

        int sum = 0;
        int count = 0;

        while (run) {
            triangleNumber++;
            sum += triangleNumber;

            count = 0;

            for (int nbr = 1; nbr < sum; nbr++) {
                if (sum % nbr == 0) {
                    if ((sum / nbr) > nbr) {
                        count += 2;
                    } else {
                        break;
                    }
                }
            }

            if (count > 500) {
                run = false;

            }
        }

        System.out.println(System.currentTimeMillis() - time + " millis");
        System.out.println("Nbr " + triangleNumber + " with sum " + sum + " has " + count + " factors");
    }
}
